//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursov.bv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ID { get; set; }
        public string Titles { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> Price { get; set; }
        public string Photo { get; set; }
        public int IDOwner { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Address { get; set; }
        public int NumberFloors { get; set; }
        public Nullable<int> IDContract { get; set; }
        public int IDMicrodistrict { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Microdistrict Microdistrict { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
