//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursov.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Microdistrict
    {
        public int ID { get; set; }
        public string Microdistrict1 { get; set; }
        public Nullable<int> IDCity { get; set; }
    
        public virtual City City { get; set; }
    }
}
